name: necmedical_app
description: NEC Medical & Allied Industry mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'   # compatible with Flutter 3.35.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  webview_flutter: ^4.9.0
  flutter_riverpod: ^2.6.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  html: ^0.15.4
  shimmer: ^3.0.0
  lottie: ^3.3.3
  internet_connection_checker_plus: ^3.1.1
  flutter_file_downloader: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/nec_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/nec_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/nec_logo.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/images/nec_logo.png"
